name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.VL_BOT_TOKEN }}
